deploy:
  - provider: s3
    cache_control: 'no-cache, max-age=0' # no cache and revalidate
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $BUCKET_DEV
    acl: public_read
    local_dir: public
    skip_cleanup: true
    on:
      branch: 'develop'
  - provider: s3
    cache_control: 'max-age=0' # 1 month
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $BUCKET_PROD
    acl: public_read
    local_dir: public
    skip_cleanup: true
    on:
      branch: 'master'
language: node_js
node_js: 10.16.2
cache:
  directories:
    - node_modules
dist: trusty
install: npm install && npm install -g gatsby-cli
script:
  - |
    if [ "$TRAVIS_BRANCH" = "develop" ]; then
      echo "Building with Contentful Preview API"
      CONTENTFUL_ENV=development npm run build-dev
    elif [ "$TRAVIS_BRANCH" = "master" ]; then
      echo "Building with Contentful Content API"
      CONTENTFUL_ENV=production npm run build
    fi
before_deploy: npm test
after_deploy:
  echo $TRAVIS_BRANCH
  echo $AWS_CLOUDFRONT_DIST_ID
after_deploy: ./travis/clear_cf_cache.sh