deploy:
  - provider: s3
    cache_control: 'no-cache, max-age=0' # no cache and revalidate
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $BUCKET_DEV
    acl: public_read
    local_dir: public
    skip_cleanup: true
    on:
      branch: 'develop'
  - provider: s3
    cache_control: 'max-age=2628000' # 1 month
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $BUCKET_PROD
    acl: public_read
    local_dir: public
    skip_cleanup: true
    on:
      branch: 'master'
language: node_js
node_js: 10.16.2
cache:
  directories:
    - node_modules
dist: trusty
install: npm install
script: npm run build
before_deploy: npm install -g gatsby-cli
